http://iamtrask.github.io/2015/07/12/basic-python-network/ 

In [1]:
import numpy as np

In [35]:
X = np.array([[0,0,1],
            [0,1,1],
            [1,0,1],
            [1,1,1]])
                
y = np.array([[0],
              [1],
              [1],
              [0]])

np.random.seed(1)

def sigmoid(x):
    return 1/(1 + np.exp(-x))

def sigmoid_derivative(x):
    return x*(1-x)
    
    
# randomly initialize our weights 
weights_0 = np.random.random((3,4))
weights_1 = np.random.random((4,1))

print("Random weights_0 initialization:")
print(weights_0)
print('')
print("Random weights_1 initialization:")
print(weights_1)
print('')
print("********** start training **********")
print('')

# set the epoch value to 50,000. This is just an arbitrary number. 
# Feel free to try more values and see if the network trains better (error value decreases)

for j in range(50000):

    # Feed forward through layers 0, 1, and 2
    layer_0 = X # the input matrix
    layer_1 = sigmoid(np.dot(layer_0,weights_0))
    y_hat = sigmoid(np.dot(layer_1,weights_1)) # the prediction

    # calculate the error: how far is our prediction from the target value?
    l2_error = y - y_hat
        
    # in what direction is the target value?
    # were we really sure? if so, don't change too much.
    l2_delta = l2_error * sigmoid_derivative(y_hat)

    # how much did each layer_1 value contribute to the l2 error (according to the weights)?
    l1_error = l2_delta.dot(weights_1.T)
    
    # in what direction is the target l1?
    # were we really sure? if so, don't change too much.
    l1_delta = l1_error * sigmoid_derivative(layer_1)

    weights_1 += layer_1.T.dot(l2_delta)
    weights_0 += layer_0.T.dot(l1_delta)
    
    # print the error and weights values every 10,000 epochs
    if (j% 10000) == 0:
        print("Weights values at layer 1:")
        print(weights_0)
        print("")   
        print("Weights values at layer 2:")
        print(weights_1)
        print("")   
        print ("Error ======> " + str(np.mean(np.abs(l2_error))))
        print("============================================================================")
        print("")

Random weights_0 initialization:
[[4.17022005e-01 7.20324493e-01 1.14374817e-04 3.02332573e-01]
 [1.46755891e-01 9.23385948e-02 1.86260211e-01 3.45560727e-01]
 [3.96767474e-01 5.38816734e-01 4.19194514e-01 6.85219500e-01]]

Random weights_1 initialization:
[[0.20445225]
 [0.87811744]
 [0.02738759]
 [0.67046751]]

********** start training **********

Weights values at layer 1:
[[ 4.13303021e-01  7.07247003e-01 -4.57394850e-04  2.92787658e-01]
 [ 1.43453123e-01  8.20760485e-02  1.85714654e-01  3.36683361e-01]
 [ 3.88129145e-01  5.05349760e-01  4.17963479e-01  6.60138925e-01]]

Weights values at layer 2:
[[ 0.07847336]
 [ 0.74216518]
 [-0.09212278]
 [ 0.53192674]]

Error ======> 0.4991685688467836

Weights values at layer 1:
[[ 7.1761412   6.24202472 -3.18097236  1.68278777]
 [-3.34754201  6.23214909  7.13675873  1.79082995]
 [ 0.17907778 -1.21589433  0.02540937 -2.6421992 ]]

Weights values at layer 2:
[[-7.98214791]
 [13.2662962 ]
 [-7.92618625]
 [-2.44240948]]

Error ======> 0.0126415