In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import UpSampling2D

Using TensorFlow backend.


In [2]:
# input data
X = np.asarray([[1, 2],
             [3, 4]])

print(X)

[[1 2]
 [3 4]]


In [3]:
# reshape input data 
X = X.reshape((1, 2, 2, 1))

In [4]:
# define model
model = Sequential()
model.add(UpSampling2D(size=(3,3),input_shape=(2, 2, 1)))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
up_sampling2d_1 (UpSampling2 (None, 6, 6, 1)           0         
Total params: 0
Trainable params: 0
Non-trainable params: 0
_________________________________________________________________


In [5]:
# model output
output = model.predict(X)
output = output.reshape((6, 6))
print(output)

[[1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [1. 1. 1. 2. 2. 2.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]
 [3. 3. 3. 4. 4. 4.]]
